language: php

php:
    - 5.4
    - 5.5
    - 5.6

branches:
    only:
        - master

before_script:
    - composer install

script:
    - bin/phpcs Api DependencyInjection --standard=PSR2 --extensions=php
    - phpunit
