language: php

php:
    - 5.4
    - 5.5

branches:
    only:
        - master

before_script:
    - composer install

script:
    - php -l src
    - bin/phpcs src --standard=PSR2 --extensions=php
    - phpunit
